version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 3306:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=user
      - POSTGRES_DB=skill_profile_db
    expose:
      # Opens port 3306 on the container
      - '3306'